services:

  db:
    image: postgres:17
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  cache:
    image: redis:latest
    restart: always
    volumes:
      - ./data/cache:/data

  web:
    build: .
    restart: always
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=django_project.settings.prod
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
      - SECRET_KEY=enter-your-secret-key
    depends_on:
      - db
