# Generated by Django 5.2.15 on 2026-07-08 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='learner',
            name='is_editor',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='learner',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='learner',
            name='username',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
